#!/usr/bin/env bash
set -euo pipefail

rm -rf results reports

./run -j8 assemble
gzip -dc resources/mock_assembly.fa.gz > results/assemble/renaming/all.fa
./run -j8 bin
mkdir --parents results/dereplicate/drep/dereplicated_genomes
gzip -dc resources/mock_assembly.fa.gz > results/dereplicate/drep/dereplicated_genomes/all:bin_00001.fa
touch results/dereplicate/drep/dereplicated_genomes/.snakemake_timestamp
./run -j8 dereplicate
./run -j8 report
