#!/usr/bin/env bash
set -euo pipefail

rm -rf results reports

./run -j8 assemble__megahit

gzip -dc resources/mock_assembly.fa.gz > results/assemble/renaming/all.fa

./run -j8 assemble__magscot --rerun-triggers mtime

mkdir --parents results/assemble/drep/separated_bins
touch results/assemble/drep/separated_bins/.snakemake_timestamp
gzip -dc resources/mock_assembly.fa.gz > results/assemble/drep/separated_bins/all:bin_00001.fa

mkdir --parents results/assemble/drep/dereplicated_genomes
touch results/assemble/drep/dereplicated_genomes/.snakemake_timestamp
gzip -dc resources/mock_assembly.fa.gz > results/assemble/drep/dereplicated_genomes/all:bin_00001.fa

touch results/assemble/drep/data.tar.gz
touch results/assemble/drep/data_tables.tar.gz

gzip -dc resources/mock_assembly.fa.gz > results/assemble/drep/dereplicated_genomes.fa


./run -j8 dereplicate --rerun-triggers mtime

./run -j8 report
