include: "common/bowtie2.smk"
include: "common/coverm_contig.smk"
include: "common/coverm_genome.smk"
include: "common/concatenate.smk"
include: "common/csvtk.smk"
include: "common/multiqc.smk"
include: "common/quast.smk"
