# Execution parameters
---
preprocess:
  fastp:
    extra: "--length_required 75 --trim_poly_g --trim_poly_x"
  bowtie2:
    bowtie2_extra: ""
    samtools_extra: "-m 1G"
  bracken:
    read_length: 150
    threshold: 10

assemble:
  megahit:
    extra: "--min-contig-len 1500"  # --presets meta-large
  samtools:
    mem: 1G

# common both to prokaryotes and viruses
quantify:
  bowtie2:
    samtools_mem: 1G
  coverm:   # https://github.com/wwood/CoverM#calculation-methods
    genome:
      separator: "@"
      extra: "--min-covered-fraction 0"
    # contig:
    #   methods: ["count", "covered_bases"]

prokaryotes:
  annotate:
    bakta:
      extra: ""
    drep:
      secondary_anis:
        - 0.95
        - 0.98
        - 0.99
      minimum_completeness: 75
      maximum_contamination: 25
    dram:
      annotate:
        min_contig_size: 1500


viral:
  mvp:
    genomad_checkv:  # MVP_01
      min_seq_size: 0
      genomad_mode: ""  # "", --genomad_relaxed, or --genomad_conservative
    filter:  # MVP_02
      viral_min_genes: 1
      host_viral_genes_ratio: 1
    clustering:  # MVP_03
      min_ani: 95
      min_tcov: 85
      min_qcov: 0
      read_type: short
    read_mapping:  # MVP_04
      read_type: short
      interleaved: "FALSE"
    votu_table:  # MVP_05
      covered_fraction: [0.1, 0.5, 0.9]
      normalization: RPKM
      filtration: conservative
      viral_min_genes: 1
      host_viral_genes_ratio: 1
    functional_annotation:  # MVP_06
      fasta_files: representative
      phrogs_evalue: 0.01
      phrogs_score: 50
      pfam_evalue: 0.01
      pfam_score: 50
    binning:  # MVP_07
      normalization: RPKM
      filtration: conservative
      viral_min_genes: 0
      host_viral_genes_ratio: 1
      read_type: short
      interleaved: "FALSE"
