# Run tests over snakefile workflow
---
name: Tests

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main, devel]
  pull_request:
    branches: [main, devel]

env:
  CACHE_NUMBER: 0  # Increment this number to invalidate the cache

jobs:

  Pre-Commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          lfs: 'true'
      - name: Run pre-commit on all files
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

  Testing:
    runs-on: ubuntu-latest
    needs:
      - Pre-Commit
    steps:

      - uses: actions/checkout@v6
        with:
          lfs: 'true'

      - name: Set up caches
        uses: actions/cache@v5
        with:
          path: |
            .snakemake/conda
            ~/.cache/pre-commit/
          key: snakemake-conda

      - name: Clean conda cache
        run: conda clean --all --yes

      - name: Test workflow - Test
        uses: snakemake/snakemake-github-action@v2
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: >
            --use-conda
            --profile profile/default
            --show-failed-logs
            --cores 3
            --latency-wait 5
            --printshellcmds
            --dry-run
            test

      - name: Test workflow - Print the commands to everything else
        uses: snakemake/snakemake-github-action@v2
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: >
            --use-conda
            --profile profile/default
            --show-failed-logs
            --cores 3
            --latency-wait 5
            --printshellcmds
            --dry-run
            all

      # - name: Delete everything
      #   run: |
      #     sudo find results -not -name "*.log" -type f -delete -print

      - name: Clean conda
        run: conda clean --all --yes

      - name: Give permissions to cache
        run: sudo chown -R $USER:$USER .snakemake/conda

      - uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: results
          path: |
            results/**/*.log*
            # results/
            # reports/
            # !**/*.cram
            # !**/*.fq.gz
            # !**/*.bam
            # !**/*.bt2
