#!/usr/bin/env bash
set -euo pipefail

rm -rf results reports

function run() {
    snakemake \
        --use-conda \
        --profile profile/default \
        --rerun-triggers mtime \
        --cache \
        --cores 8 \
        "$@"
}

run \
    --jobs 8 \
    report__step__preprocess \
    assemble__megahit

# generate mock assembly
mkdir --parents results/assemble/megahit
cp \
    --verbose \
    --force \
    resources/mock_assembly.fa.gz \
    results/assemble/megahit/all.fa.gz

run \
    prokaryotes__cluster__concoct \
    prokaryotes__cluster__metabat2 \
    prokaryotes__cluster__maxbin2

# skip magscot

# Skip drep-related results
mkdir --parents results/prokaryotes/cluster/drep/dereplicated_genomes
touch results/prokaryotes/cluster/drep/dereplicated_genomes/.snakemake_timestamp
cp \
    --verbose \
    resources/mock_assembly.fa.gz \
    results/prokaryotes/cluster/drep/dereplicated_genomes/all:bin_00001.fa.gz
cp \
    --verbose \
    resources/mock_assembly.fa.gz \
    results/prokaryotes/cluster/drep/dereplicated_genomes.fa.gz

run \
    prokaryotes__quantify \
    report__step__quantify

run \
    prokaryotes__annotate__quast

run \
    viruses

run \
    report
