#!/usr/bin/env bash
set -euo pipefail

rm -rf results reports

./run \
    --jobs 8 \
    preprocess__bowtie2 \
    preprocess__fastp \
    preprocess__kraken2 \
    preprocess__samtools \

./run \
    --jobs 8 \
    assemble__megahit

# generate mock assembly
cp \
    resources/mock_assembly.fa.gz \
    results/assemble/megahit/all.fa.gz

./run \
    --jobs 8 \
    assemble__magscot \
    --rerun-triggers mtime

# Skip drep-related results
mkdir --parents results/prokaryotes/cluster/drep/
cp \
    resources/mock_assembly.fa.gz \
    results/prokaryotes/cluster/drep/dereplicated_genomes.fa.gz

./run \
    --jobs 8 \
    quantify \
    --rerun-triggers mtime

./run \
    --jobs 8 \
    annotate__quast \
    --rerun-triggers mtime

./run \
    --jobs 4 \
    viral \
    --rerun-triggers mtime

./run \
    --jobs 8 \
    report \
    --rerun-triggers mtime
