#!/usr/bin/env bash
set -euo pipefail

rm -rf results reports

./run \
    --jobs 8 \
    preprocess__bowtie2 \
    preprocess__fastp \
    preprocess__kraken2 \
    preprocess__samtools \

./run \
    --jobs 8 \
    assemble__megahit

# generate mock assembly
cp \
    resources/mock_assembly.fa.gz \
    results/assemble/megahit/all.fa.gz

./run \
    --jobs 8 \
    assemble__magscot \
    --rerun-triggers mtime

# generate mock magscot results
mkdir --parents results/assemble/drep/dereplicated_genomes
touch results/assemble/drep/dereplicated_genomes/.snakemake_timestamp
cp resources/mock_assembly.fa.gz results/assemble/drep/dereplicated_genomes/all:bin_00001.fa.gz

./run \
    --jobs 8 \
    quantify \
    --rerun-triggers mtime
./run \
    --jobs 8 \
    annotate__quast \
    --rerun-triggers mtime

./run \
    --jobs 8 \
    report \
    --rerun-triggers mtime
